FROM node:14-alpine as base

WORKDIR /var/www
COPY ../package*.json /

FROM base as production
ENV NODE_ENV=production
RUN npm ci
CMD ["npm", "run" ,"start:prod"]


FROM base as dev
ENV NODE_ENV=development
RUN npm install -g nodemon && npm install
CMD ["npm", "run" ,"start:dev"]
